# Site settings
title: Keep Ruby Weird
email: organizers@keeprubyweird.com
description: "Austin's newest Ruby conference: One day and filled with weird."
url: "http://keeprubyweird.com"
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock']

# Build settings
markdown: redcarpet
permalink: ':title'
